defaults:
    - _self_
    - watermark_args: unigram

results_dir: "./eval/results"
model_cache_dir: "./.cache"

prompt: "Write a 250 word essay on the role of power and its impact on characters in the Lord of the Rings series. How does the ring symbolize power, and what does Tolkien suggest about the nature of power?"

generator_args:
    model_name_or_path: "TheBloke/Llama-2-7B-Chat-GPTQ"
    revision: "main"
    device_map: "cuda"
    trust_remote_code: False
    max_new_tokens: 1024
    do_sample: True 
    temperature: 0.7 
    top_p: 0.95 
    top_k: 40
    repetition_penalty: 1.1

oracle_args:
    use_query: True
    use_gpt: False
    check_quality: False
    choice_granularity: 5
    use_chat_arena_prompt: False
    reward_model: "OpenAssistant/reward-model-deberta-v3-large-v2"
    model_cache_dir: "${model_cache_dir}"

mutator_args:
    model_name_or_path: "TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ"
    revision: "main" # "gptq-3bit-128g-actorder_True" for 3-bit version
    device_map: "${generator_args.device_map}"
    max_new_tokens: "${generator_args.max_new_tokens}"
    do_sample: "${generator_args.do_sample}" 
    temperature: "${generator_args.temperature}"
    top_p: "${generator_args.top_p}"
    top_k: "${generator_args.top_k}"
    repetition_penalty: "${generator_args.repetition_penalty}"
    model_cache_dir: "${model_cache_dir}"
    num_steps: 100
    patience: 25
    save_name: "${results_dir}/attack_{time_stamp}.csv"