watermarker: "umd"
mutator_type: "SentenceMutator"
oracle_type: "DiffOracle"

is_completion: False

attack:
  use_max_steps: True
  max_steps: 300
  target_mutations: 20
  use_backtrack: True
  backtrack_patience: 25
  patience: 75
  length_variance: 0.05
  log_csv_path: './08_21_attack_test.csv'
  verbose: False




  





