import guidance
from guidance import gen, select, user, system, assistant
from distinguisher.models.base import Distinguisher

class ReasoningDistinguisher(Distinguisher):
    @staticmethod
    @guidance
    def prompt_fn(lm, persona, **kwargs):
        if persona:
            with system():
                lm += f"{persona}"
        with user():
            lm += f"""
            ### Task Description:
            1. Read the following 3 responses. They are labelled "A", "B", and "P".
            2. "A" and "B" are original responses, and "P" was generated by perturbing one of the original responses.
            3. Identify which of the original responses the perturbed story was derived from.
            4. Before responding, please provide a brief one-sentence explanation of your reasoning.
            
            Original response A:
            {kwargs["A"]}

            Original response B:
            {kwargs["B"]}

            Perturbed response P:
            {kwargs["P"]}
            """
        with assistant():
            lm += f"""\
            I have read and analyzed the responses. Here is my reasoning for my answer: {gen("reasoning", stop='.')}.
            I believe the perturbed response P was derived from original response {select(["A", "B"], name="choice")}.
            """
        return lm

    @property
    def input_keys(self):
        return ["P"]

    @property
    def output_keys(self):
        return ["choice", "reasoning"]